import { DEFAULT_AVATAR_CONFIG, StudentData, UserStats } from '@/types';

export const DEMO_STUDENT_STATS: UserStats = {
    xp: 620,
    level: 3,
    missionsCompleted: ['cloud-cleaner', 'data-detective', 'filter-bubble-breaker'],
    inventory: ['badge_cloud', 'badge_detective'],
    avatarConfig: DEFAULT_AVATAR_CONFIG,
    hasCompletedOnboarding: true,
    hasCompletedAvatarSetup: true,
    hasCompletedStudentTutorial: true,
    studentClass: 'MH2B',
    schoolId: 'demo-school',
    yearGroup: 2,
    educationLevel: 'mavo',
    dailyStreak: 4,
    badges: ['badge_cloud', 'badge_detective'],
    completedIntroWeeks: [1, 2, 3],
};

export const DEMO_STUDENTS: StudentData[] = [
    {
        uid: 'demo-student-1',
        displayName: 'Alex D.',
        email: null,
        photoURL: null,
        role: 'student',
        identifier: 'DEMO01',
        schoolId: 'demo-school',
        studentClass: 'MH2B',
        yearGroup: 2,
        educationLevel: 'mavo',
        stats: {
            xp: 820,
            level: 4,
            missionsCompleted: ['cloud-cleaner', 'data-detective', 'datalekken-rampenplan', 'access-control-engineer'],
            inventory: ['badge_cloud', 'badge_detective'],
            studentClass: 'MH2B',
            yearGroup: 2,
            educationLevel: 'mavo',
        },
    },
    {
        uid: 'demo-student-2',
        displayName: 'Bilal M.',
        email: null,
        photoURL: null,
        role: 'student',
        identifier: 'DEMO02',
        schoolId: 'demo-school',
        studentClass: 'MH2B',
        yearGroup: 2,
        educationLevel: 'mavo',
        stats: {
            xp: 440,
            level: 2,
            missionsCompleted: ['cloud-cleaner', 'data-detective'],
            inventory: ['badge_cloud'],
            studentClass: 'MH2B',
            yearGroup: 2,
            educationLevel: 'mavo',
        },
    },
    {
        uid: 'demo-student-3',
        displayName: 'Sara J.',
        email: null,
        photoURL: null,
        role: 'student',
        identifier: 'DEMO03',
        schoolId: 'demo-school',
        studentClass: 'MH2B',
        yearGroup: 2,
        educationLevel: 'mavo',
        stats: {
            xp: 1050,
            level: 5,
            missionsCompleted: [
                'cloud-cleaner',
                'data-detective',
                'datalekken-rampenplan',
                'access-control-engineer',
                'filter-bubble-breaker',
            ],
            inventory: ['badge_cloud', 'badge_detective'],
            studentClass: 'MH2B',
            yearGroup: 2,
            educationLevel: 'mavo',
        },
    },
    {
        uid: 'demo-student-4',
        displayName: 'Noah K.',
        email: null,
        photoURL: null,
        role: 'student',
        identifier: 'DEMO04',
        schoolId: 'demo-school',
        studentClass: 'MH2B',
        yearGroup: 2,
        educationLevel: 'mavo',
        stats: {
            xp: 120,
            level: 1,
            missionsCompleted: [],
            inventory: [],
            studentClass: 'MH2B',
            yearGroup: 2,
            educationLevel: 'mavo',
        },
    },
    {
        uid: 'demo-student-5',
        displayName: 'Lena T.',
        email: null,
        photoURL: null,
        role: 'student',
        identifier: 'DEMO05',
        schoolId: 'demo-school',
        studentClass: 'MH2B',
        yearGroup: 2,
        educationLevel: 'mavo',
        stats: {
            xp: 670,
            level: 3,
            missionsCompleted: ['cloud-cleaner', 'filter-bubble-breaker', 'access-control-engineer'],
            inventory: ['badge_cloud'],
            studentClass: 'MH2B',
            yearGroup: 2,
            educationLevel: 'mavo',
        },
    },
];
