export const sharedTailwindConfig = {
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                // DUCK-stijl homepage tokens (duck.school-geïnspireerd) — alleen
                // gebruikt door de publieke landing; lab-* blijft voor de app.
                duck: {
                    bg: '#f2f1ec',
                    bgLight: '#f8f8f5',
                    ink: '#202023',
                    acid: '#e1ff01',
                    gray: '#c2c1bd',
                    error: '#ff3c21',
                    coral: '#D97848',
                    muted: '#445865',
                    line: '#E7D8BD',
                    creamDeep: '#F3E4CB',
                },
                lab: {
                    cream: '#FCF6EA',
                    paper: '#FFFDF7',
                    creamDeep: '#F3E4CB',
                    ink: '#08283B',
                    muted: '#445865',
                    olive: '#99984D',
                    gold: '#D7C95F',
                    sage: '#5F947D',
                    coral: '#D97848',
                    tealDark: '#0B453F',
                    line: '#E7D8BD',
                    bg: '#FCF6EA',
                    surface: '#FFFDF7',
                    primary: '#D97848',
                    primaryDark: '#D97848',
                    accent: '#5F947D',
                    secondary: '#0B453F',
                    dark: '#08283B',
                    text: '#08283B',
                    textLight: '#445865',
                    brown: '#D97848',
                    otterLight: '#D97848',
                    teal: '#0B453F',
                    oliveDeep: '#99984D',
                    mutedDeep: '#445865',
                    mutedSoft: '#445865',
                    bodyDark: '#08283B',
                    creamWarm: '#F3E4CB',
                    creamFrame: '#E7D8BD',
                    mint: '#5F947D',
                    cobalt: '#0B453F',
                    green: '#5F947D',
                    purple: '#0B453F',
                    pink: '#D97848',
                    blue: '#0B453F'
                },
                slate: {
                    50: '#FCF6EA',
                    100: '#FFFDF7',
                    200: '#E7D8BD',
                    300: '#E7D8BD',
                    400: '#445865',
                    500: '#445865',
                    600: '#445865',
                    700: '#445865',
                    800: '#08283B',
                    900: '#08283B',
                    950: '#0B453F',
                },
                indigo: {
                    50: '#FCF6EA',
                    100: '#FFFDF7',
                    200: '#F3E4CB',
                    300: '#D7C95F',
                    400: '#D97848',
                    500: '#D97848',
                    600: '#D97848',
                    700: '#D97848',
                    800: '#0B453F',
                    900: '#0B453F',
                    950: '#0B453F',
                },
            },
            fontFamily: {
                sans: ['Outfit', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
                display: ['Fraunces', 'Georgia', 'Times New Roman', 'serif'],
            },
            backgroundImage: {
                'grid-pattern': "linear-gradient(to right, #E7D8BD 1px, transparent 1px), linear-gradient(to bottom, #E7D8BD 1px, transparent 1px)",
            },
            boxShadow: {
                'duck-soft': '2px 4px 24px rgba(199,197,188,0.30)',
            },
            animation: {
                'float': 'float 6s ease-in-out infinite',
                'pulse-soft': 'pulse-soft 2s ease-in-out infinite',
                'fade-in-up': 'fadeInUp 0.7s ease-out forwards',
                'fade-in-up-delay-1': 'fadeInUp 0.7s ease-out 0.1s forwards',
                'fade-in-up-delay-2': 'fadeInUp 0.7s ease-out 0.2s forwards',
                'fade-in-up-delay-3': 'fadeInUp 0.7s ease-out 0.3s forwards',
                'hero-float': 'heroFloat 6s ease-in-out infinite',
                'hero-float-delayed': 'heroFloat 6s ease-in-out 2s infinite',
                'shimmer': 'shimmer 2.5s ease-in-out infinite',
                'slide-in-right': 'slideInRight 0.8s ease-out forwards',
                'carousel-progress': 'carouselProgress 6s linear forwards',
                'typing-bounce': 'typingBounce 1.4s ease-in-out infinite',
                'sound-pulse': 'soundPulse 1.2s ease-out infinite',
                'blob-morph': 'blobMorph 12s ease-in-out infinite',
                'duck-marquee': 'duckMarquee 36s linear infinite',
                'duck-spin-slow': 'duckSpin 16s linear infinite',
                'duck-float': 'duckFloat 7s ease-in-out infinite',
                'duck-float-delayed': 'duckFloat 7s ease-in-out 2.4s infinite',
                'duck-blink': 'duckBlink 5.2s ease-in-out infinite',
                'duck-rise': 'duckRise 0.85s cubic-bezier(0.22, 1, 0.36, 1) forwards',
            },
            keyframes: {
                float: {
                    '0%, 100%': { transform: 'translateY(0)' },
                    '50%': { transform: 'translateY(-10px)' },
                },
                'pulse-soft': {
                    '0%, 100%': { opacity: 1 },
                    '50%': { opacity: 0.7 },
                },
                fadeInUp: {
                    '0%': { opacity: '0', transform: 'translateY(30px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                heroFloat: {
                    '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
                    '50%': { transform: 'translateY(-12px) rotate(0.5deg)' },
                },
                shimmer: {
                    '0%': { backgroundPosition: '-200% 0' },
                    '100%': { backgroundPosition: '200% 0' },
                },
                slideInRight: {
                    '0%': { opacity: '0', transform: 'translateX(40px)' },
                    '100%': { opacity: '1', transform: 'translateX(0)' },
                },
                carouselProgress: {
                    '0%': { width: '0%' },
                    '100%': { width: '100%' },
                },
                typingBounce: {
                    '0%, 60%, 100%': { transform: 'translateY(0)' },
                    '30%': { transform: 'translateY(-4px)' },
                },
                soundPulse: {
                    '0%': { transform: 'scale(0.8)', opacity: '0.8' },
                    '100%': { transform: 'scale(2)', opacity: '0' },
                },
                blobMorph: {
                    '0%, 100%': { borderRadius: '42% 58% 45% 55% / 50% 42% 58% 50%' },
                    '33%': { borderRadius: '55% 45% 60% 40% / 45% 55% 40% 60%' },
                    '66%': { borderRadius: '38% 62% 42% 58% / 58% 38% 62% 42%' },
                },
                duckMarquee: {
                    '0%': { transform: 'translateX(0)' },
                    '100%': { transform: 'translateX(-50%)' },
                },
                duckSpin: {
                    '0%': { transform: 'rotate(0deg)' },
                    '100%': { transform: 'rotate(360deg)' },
                },
                duckFloat: {
                    '0%, 100%': { transform: 'translateY(0)' },
                    '50%': { transform: 'translateY(-12px)' },
                },
                duckBlink: {
                    '0%, 94%, 100%': { transform: 'scaleY(1)' },
                    '96%, 98%': { transform: 'scaleY(0.08)' },
                },
                duckRise: {
                    '0%': { transform: 'translateY(115%)' },
                    '100%': { transform: 'translateY(0)' },
                },
            }
        },
    },
    plugins: [],
};
