import type { ScenarioEngineConfig } from '../types';

const config: ScenarioEngineConfig = {
    missionId: 'veilig-internet',
    title: 'Veilig Internet',
    introEmoji: '🔒',
    introTitle: 'Veilig Internet',
    introDescription:
        'Online zie je dagelijks berichten, links, inlogschermen en verzoeken om informatie. Sommige zijn echt, andere proberen je te misleiden. In deze missie oefen je met veilig gedrag: phishing herkennen, sterke wachtwoorden en 2FA kiezen, slim omgaan met persoonsgegevens en rustig reageren op social engineering.',
    missionGoal: {
        primaryGoal: 'Ik herken online gevaren en bescherm mezelf en mijn gegevens met veilige keuzes.',
        criteria: {
            type: 'rounds-complete',
            description: 'Je beoordeelt nepberichten, wachtwoorden, persoonsgegevens en de juiste stappen bij twijfel.',
        },
        evidence: 'Je legt uit hoe je phishing herkent, sterke wachtwoorden en 2FA kiest, en wanneer je hulp vraagt.',
    },
    introFeatures: [
        'Herken verdachte signalen in nepberichten',
        'Kies tussen sterke en zwakke wachtwoorden en 2FA',
        'Bepaal welke persoonsgegevens je wel of niet deelt',
        'Zet de juiste stappen bij een verdacht bericht',
    ],
    learningObjectives: [
        'Herken minstens vier phishing-signalen in een nepbericht.',
        'Vergelijk sterke en zwakke wachtwoorden en leg uit waarom 2FA extra bescherming geeft.',
        'Scheid persoonsgegevens die je veilig kunt delen van gegevens die je beter privé houdt.',
        'Zet de stappen bij een verdacht bericht in de juiste volgorde en leg je keuze uit.',
    ],
    attribution: {
        source: 'Veilig internet',
        author: 'DigitaleVaardigheden Noorderpoort',
        license: 'CC BY 3.0 NL',
        licenseUrl: 'https://creativecommons.org/licenses/by/3.0/nl/',
        sourceUrl: 'https://maken.wikiwijs.nl/105223/',
    },
    maxScore: 100,
    badges: [
        { minScore: 85, emoji: '🛡️', title: 'Internet Wachter', color: '#202023' },
        { minScore: 65, emoji: '🔍', title: 'Slimme Spotter', color: '#ff3c21' },
        { minScore: 40, emoji: '🔐', title: 'Veilige Starter', color: '#5F947D' },
        { minScore: 0, emoji: '🌱', title: 'Blijf Oefenen', color: '#99984D' },
    ],
    takeaways: [
        'Let op afzender, taal, urgentie en onverwachte links of bijlagen.',
        'Een sterk wachtwoord is lang, uniek en moeilijk te raden.',
        '2FA maakt inloggen veiliger, omdat een extra controle stap nodig is.',
        'Deel alleen persoonsgegevens als dat echt nodig en logisch is.',
        'Bij twijfel: stop, controleer rustig en vraag hulp van een vertrouwde volwassene.',
    ],
    rounds: [
        {
            id: 'phishing-signalen',
            emoji: '🚩',
            title: 'Welke signalen verraden phishing?',
            description:
                'Je krijgt een bericht dat om snelle actie vraagt. Welke onderdelen laten zien dat je extra moet opletten? Selecteer alle verdachte signalen.',
            type: 'select-correct',
            maxScore: 25,
            minSelections: 4,
            selectionInstruction: 'Selecteer de onderdelen die verdacht zijn',
            feedbackCorrect: 'Goed gezien. Je leest niet alleen de tekst, maar ook de signalen eromheen.',
            feedbackIncorrect: 'Niet elk bericht is wat het lijkt. Zoek naar druk, fouten en vreemde details.',
            items: [
                { id: 1, icon: '📧', title: 'Afzender eindigt op een onbekend domein', description: 'Het bericht lijkt van je school of een bekende app te komen, maar het adres eindigt op een vreemde domeinnaam die je nog nooit hebt gezien.', correct: true, explanation: 'Een onbekend domein is een sterk waarschuwingssignaal. Aanvallers gebruiken namen die vertrouwd klinken, maar het echte adres verraadt de afzender.' },
                { id: 2, icon: '⏰', title: 'Er staat veel druk op je', description: 'De tekst zegt dat je binnen tien minuten moet reageren, anders verlies je toegang of een prijs.', correct: true, explanation: 'Onnodige haast is een klassieke truc. Echte organisaties geven meestal tijd om iets rustig te controleren.' },
                { id: 3, icon: '🔗', title: 'De knop stuurt je naar een andere site', description: 'De knop zegt dat je moet inloggen, maar het webadres dat je ziet klopt niet met de echte dienst.', correct: true, explanation: 'Een link kan anders zijn dan de tekst laat zien. Als het adres niet klopt, is het verdacht.' },
                { id: 4, icon: '✍️', title: 'De tekst bevat vreemde fouten', description: 'Er staan merkwaardige zinsbouwfouten en rare woorden in een bericht dat zogenaamd van een officiële organisatie komt.', correct: true, explanation: 'Fouten zijn niet altijd bewijs, maar in combinatie met andere signalen wel een sterke aanwijzing voor phishing.' },
                { id: 5, icon: '🏫', title: 'Je docent stuurt een opdracht via het schoolplatform', description: 'Je docent plaatst een duidelijke opdracht in het officiële leerplatform van de school, zonder rare link of gegevensverzoek.', correct: false, explanation: 'Dit is normaal schoolverkeer. Let natuurlijk wel op of je in het echte platform zit, maar op zichzelf is dit niet verdacht.' },
                { id: 6, icon: '🎁', title: 'Een gratis prijs zonder reden', description: 'Je “wint” ineens een cadeau, terwijl je nergens aan hebt meegedaan. Je moet alleen nog even je gegevens invullen.', correct: true, explanation: 'Ongevraagde prijzen zijn vaak lokmiddelen. Het doel is vaak dat je gegevens invult of op een gevaarlijke link klikt.' },
            ],
        },
        {
            id: 'wachtwoord-en-2fa',
            emoji: '🔐',
            title: 'Sterk of zwak?',
            description: 'Kijk naar elke uitspraak en beslis of die veilig is. Let extra op wachtwoorden, hergebruik en twee-factor-authenticatie.',
            type: 'binary-choice',
            maxScore: 25,
            acceptLabel: 'Veilig',
            rejectLabel: 'Onveilig',
            feedbackCorrect: 'Juist. Je kiest voor bescherming in plaats van gemak op korte termijn.',
            feedbackIncorrect: 'Kijk nog eens: een veilige keuze voelt misschien minder snel, maar beschermt je wel beter.',
            items: [
                { id: 1, icon: '🧩', title: '“Ik gebruik voor elke site hetzelfde wachtwoord.”', description: 'Je hoeft maar één wachtwoord te onthouden, maar als één account lekt, zijn ook je andere accounts kwetsbaar.', correct: false, explanation: 'Wachtwoordhergebruik is onveilig. Als een wachtwoord uitlekt, kunnen aanvallers het op meerdere plekken proberen.' },
                { id: 2, icon: '🔑', title: '“Mijn wachtwoord is lang, uniek en bestaat uit een zin.”', description: 'Je gebruikt een lange, zelfbedachte wachtwoordzin die je nergens anders inzet.', correct: true, explanation: 'Dat is sterk: lang, uniek en moeilijk te raden. Een wachtwoordzin is vaak beter te onthouden dan losse tekens.' },
                { id: 3, icon: '📲', title: '“Ik zet 2FA aan als die optie er is.”', description: 'Naast het wachtwoord moet je nog een extra stap bevestigen, bijvoorbeeld via een app of code.', correct: true, explanation: '2FA maakt het veel moeilijker om binnen te komen met alleen een gestolen wachtwoord.' },
                { id: 4, icon: '📅', title: '“Ik verander mijn wachtwoord alleen als iemand het vraagt.”', description: 'Je wacht af tot er een probleem is, in plaats van vooraf veilig te werken.', correct: false, explanation: 'Beter is om al preventief veilig te werken: sterke unieke wachtwoorden en waar mogelijk 2FA.' },
                { id: 5, icon: '📝', title: '“Ik schrijf mijn wachtwoord op een briefje naast mijn laptop.”', description: 'Handig om te onthouden, maar ook zichtbaar voor anderen die bij je bureau komen.', correct: false, explanation: 'Een zichtbaar briefje is onveilig. Gebruik liever een veilige manier om wachtwoorden op te slaan of onthoud een wachtwoordzin.' },
                { id: 6, icon: '🛡️', title: '“2FA is een extra slot boven op mijn wachtwoord.”', description: 'Zelfs als iemand je wachtwoord kent, is er nog een tweede controle nodig.', correct: true, explanation: 'Dat is precies waarom 2FA zo nuttig is: een extra beveiligingslaag bovenop je wachtwoord.' },
            ],
        },
        {
            id: 'persoonsgegevens',
            emoji: '🪪',
            title: 'Welke gegevens houd je privé?',
            description: 'Sommige gegevens kun je best delen, andere houd je liever voor jezelf. Selecteer de gegevens die je beter niet zomaar online zet.',
            type: 'select-correct',
            maxScore: 25,
            minSelections: 4,
            selectionInstruction: 'Selecteer alle gegevens die je privé houdt',
            feedbackCorrect: 'Slim. Je ziet dat niet alles voor iedereen bedoeld is.',
            feedbackIncorrect: 'Kijk nog eens naar welke gegevens een ander echt nodig heeft en welke niet.',
            items: [
                { id: 1, icon: '🏠', title: 'Je thuisadres', description: 'Met een adres kan iemand weten waar je woont en wanneer je daar bent.', correct: true, explanation: 'Een thuisadres is gevoelige informatie. Deel het alleen als het echt noodzakelijk is en met de juiste persoon.' },
                { id: 2, icon: '🎂', title: 'Je exacte geboortedatum', description: 'Je geboortedatum kan helpen om een account te misbruiken of je identiteit te raden.', correct: true, explanation: 'Samen met andere gegevens kan een geboortedatum misbruikt worden. Houd dit dus liever privé.' },
                { id: 3, icon: '📸', title: 'Een foto van je huisdier', description: 'Een gewone foto van je hond, kat of konijn vertelt niet veel over je privacy.', correct: false, explanation: 'Dit is meestal niet gevoelig. Niet elk stukje content is een persoonsgegeven dat je moet verbergen.' },
                { id: 4, icon: '☎️', title: 'Je persoonlijke telefoonnummer', description: 'Je nummer kan gebruikt worden om je direct te benaderen of te misbruiken voor spam.', correct: true, explanation: 'Een telefoonnummer is persoonlijk en kan worden misbruikt. Deel het alleen als het echt nodig is.' },
                { id: 5, icon: '🎮', title: 'Je favoriete game', description: 'Dit zegt meer over je smaak dan over je veiligheid.', correct: false, explanation: 'Een hobby of voorkeur is meestal geen gevoelig persoonsgegeven. Denk vooral aan informatie waarmee iemand je kan vinden of imiteren.' },
                { id: 6, icon: '📧', title: 'Je inlogmail voor school', description: 'Een e-mailadres voor inloggen is vaak gekoppeld aan andere accounts en diensten.', correct: true, explanation: 'Je inlogmail is een sleutel tot je accounts en hoort daarom beschermd te blijven.' },
            ],
        },
        {
            id: 'verdacht-bericht',
            emoji: '🧭',
            title: 'Wat doe je eerst?',
            description: 'Je krijgt een verdacht bericht van iemand die zich voordoet als een bekende. Zet de juiste stappen in de beste volgorde.',
            type: 'order-priority',
            maxScore: 25,
            orderInstruction: 'Klik de stappen aan in de volgorde waarin je ze slim uitvoert',
            feedbackCorrect: 'Heel goed. Je blijft rustig en beschermt jezelf voordat je iets deelt.',
            feedbackIncorrect: 'Denk aan de volgorde: eerst stoppen en controleren, daarna pas melden of delen.',
            items: [
                { id: 1, icon: '✋', title: 'Stop en klik nog niets', description: 'Neem even pauze voordat je reageert, typt of op links drukt.', correctPosition: 0, explanation: 'Een korte pauze voorkomt dat je automatisch op de valstrik ingaat.' },
                { id: 2, icon: '🔍', title: 'Controleer afzender en inhoud', description: 'Kijk naar het adres, de toon, de link en of het verzoek logisch is.', correctPosition: 1, explanation: 'Controle is belangrijk voordat je iets deelt of installeert. Je zoekt naar afwijkingen.' },
                { id: 3, icon: '👩‍🏫', title: 'Vraag een vertrouwde volwassene om hulp', description: 'Laat een ouder, docent of mentor meekijken als je twijfelt.', correctPosition: 2, explanation: 'Samen kijken voorkomt fouten. Social engineering werkt juist als je alleen en gehaast bent.' },
                { id: 4, icon: '🚩', title: 'Meld of blokkeer indien nodig', description: 'Gebruik de meldknop of blokkeer het account als het onveilig blijkt.', correctPosition: 3, explanation: 'Melden helpt anderen en kan misbruik stoppen. Blokkeren beschermt jou direct.' },
            ],
        },
    ],
};

export default config;
