/**
 * AI Content Marker — EU AI Act Art. 50(2) compliance
 * 
 * Embeds machine-readable provenance metadata in AI-generated content.
 * Ensures all AI-generated text and images carry traceable origin labels
 * as required by the EU AI Act transparency obligations.
 */

// ============================================================================
// TYPES
// ============================================================================

export interface AiProvenanceMetadata {
    /** The system that generated the content */
    generator: string;
    /** The AI model used */
    model: string;
    /** ISO 8601 timestamp of generation */
    timestamp: string;
    /** Type of generated content */
    type: 'text' | 'image' | 'mixed';
    /** Standard disclaimer */
    disclaimer: string;
    /** Version of the provenance schema */
    schema_version: string;
}

// ============================================================================
// CONSTANTS
// ============================================================================

const GENERATOR_ID = 'DGSkills/2.0';
const SCHEMA_VERSION = '1.0.0';
const DEFAULT_DISCLAIMER_NL = 'AI-gegenereerd — kan fouten bevatten';

// ============================================================================
// TEXT MARKING
// ============================================================================

/**
 * Wrap AI-generated text with machine-readable provenance metadata.
 * Embeds a JSON-LD compatible metadata block as an HTML comment.
 * 
 * @param text - The AI-generated text content
 * @param model - The model identifier (e.g., 'gemini-pro', 'gemini-flash')
 * @returns The text with embedded provenance metadata
 */
export const markAiGeneratedText = (
    text: string,
    model: string = 'gemini'
): string => {
    const metadata = buildMetadata('text', model);
    return `<!-- AI_PROVENANCE:${JSON.stringify(metadata)} -->\n${text}`;
};

/**
 * Extract provenance metadata from marked AI-generated text.
 * Returns null if no metadata is found.
 */
export const extractAiProvenance = (
    markedText: string
): AiProvenanceMetadata | null => {
    const match = markedText.match(/<!-- AI_PROVENANCE:(.*?) -->/);
    if (!match) return null;

    try {
        return JSON.parse(match[1]) as AiProvenanceMetadata;
    } catch {
        return null;
    }
};

/**
 * Strip provenance metadata from marked text, returning clean text.
 */
export const stripAiProvenance = (markedText: string): string => {
    return markedText.replace(/<!-- AI_PROVENANCE:.*? -->\n?/, '');
};

// ============================================================================
// IMAGE MARKING (preparatory — full C2PA pending)
// ============================================================================

/**
 * Create provenance metadata for an AI-generated image.
 * Currently logs metadata for audit trail; full C2PA integration pending.
 * 
 * When C2PA is integrated, this will embed Content Credentials
 * directly in the image binary (JPEG/PNG EXIF/XMP).
 */
export const createImageProvenance = (
    model: string = 'imagen'
): AiProvenanceMetadata => {
    return buildMetadata('image', model);
};

/**
 * Generate a provenance attribution string for UI display.
 * Complements the AiDisclosureBadge component with structured data.
 */
export const getAttributionText = (
    model: string = 'gemini',
    locale: 'nl' | 'en' = 'nl'
): string => {
    const timestamp = new Date().toLocaleString(locale === 'nl' ? 'nl-NL' : 'en-GB');

    if (locale === 'nl') {
        return `Gegenereerd door ${GENERATOR_ID} (model: ${model}) op ${timestamp}. ${DEFAULT_DISCLAIMER_NL}`;
    }
    return `Generated by ${GENERATOR_ID} (model: ${model}) at ${timestamp}. AI-generated — may contain errors.`;
};

// ============================================================================
// INTERNAL HELPERS
// ============================================================================

const buildMetadata = (
    type: 'text' | 'image' | 'mixed',
    model: string
): AiProvenanceMetadata => ({
    generator: GENERATOR_ID,
    model,
    timestamp: new Date().toISOString(),
    type,
    disclaimer: DEFAULT_DISCLAIMER_NL,
    schema_version: SCHEMA_VERSION,
});
