-- GEGENEREERD DOOR scripts/sync-avatar-shop-seed.mjs — NIET MET DE HAND BEWERKEN.
-- Bron: src/config/avatarCatalog.ts
--
-- Alleen de prijs is hier gezaghebbend. Labels staan erbij zodat een beheerder
-- in de database kan zien wat een id voorstelt; de UI leest ze uit TypeScript.

INSERT INTO public.avatar_shop_items (id, slot, value, label, price, gender, sort_order) VALUES
  ('gender_male', 'gender', 'male', 'Jongen', 0, NULL, 0),
  ('gender_female', 'gender', 'female', 'Meisje', 0, NULL, 1),
  ('model_std', 'baseModel', 'standard', 'Standaard', 0, NULL, 2),
  ('model_slim', 'baseModel', 'slim', 'Sportief', 0, NULL, 3),
  ('model_bot', 'baseModel', 'robot', 'Robot', 500, NULL, 4),
  ('skin_pale', 'skinColor', '#f5d0b0', 'Licht', 0, NULL, 5),
  ('skin_fair', 'skinColor', '#ffe0bd', 'Crème', 0, NULL, 6),
  ('skin_tan', 'skinColor', '#d18a6a', 'Getint', 0, NULL, 7),
  ('skin_olive', 'skinColor', '#c68642', 'Olijf', 0, NULL, 8),
  ('skin_brown', 'skinColor', '#a0522d', 'Bruin', 0, NULL, 9),
  ('skin_dark', 'skinColor', '#8d5524', 'Donker', 0, NULL, 10),
  ('skin_ebony', 'skinColor', '#614335', 'Ebben', 0, NULL, 11),
  ('hair_short', 'hairStyle', 'short', 'Kort', 0, 'male', 12),
  ('hair_spiky', 'hairStyle', 'spiky', 'Stekeltjes', 0, 'male', 13),
  ('hair_buzzcut', 'hairStyle', 'buzzcut', 'Buzz Cut', 50, 'male', 14),
  ('hair_messy', 'hairStyle', 'messy', 'Wild', 75, 'male', 15),
  ('hair_curls', 'hairStyle', 'curls', 'Krullen', 75, 'male', 16),
  ('hair_fade', 'hairStyle', 'fade', 'Opscheer', 100, 'male', 17),
  ('hair_sidepart', 'hairStyle', 'sidepart', 'Zijscheiding', 100, 'male', 18),
  ('hair_afro_m', 'hairStyle', 'afro', 'Afro', 125, 'male', 19),
  ('hair_mohawk', 'hairStyle', 'mohawk', 'Mohawk', 200, 'male', 20),
  ('hair_pigtails', 'hairStyle', 'pigtails', 'Staartjes', 0, 'female', 21),
  ('hair_long', 'hairStyle', 'long', 'Lang Sluik', 0, 'female', 22),
  ('hair_bob', 'hairStyle', 'bob', 'Boblijn', 75, 'female', 23),
  ('hair_braids', 'hairStyle', 'braids', 'Vlechtjes', 75, 'female', 24),
  ('hair_curls_f', 'hairStyle', 'curls', 'Krullen', 75, 'female', 25),
  ('hair_ponytail', 'hairStyle', 'ponytail', 'Paardenstaart', 100, 'female', 26),
  ('hair_bun', 'hairStyle', 'bun', 'Knotje', 125, 'female', 27),
  ('hair_afro_f', 'hairStyle', 'afro', 'Afro', 125, 'female', 28),
  ('haircol_black', 'hairColor', '#08283B', 'Zwart', 0, NULL, 29),
  ('haircol_darkbrown', 'hairColor', '#8B4513', 'Donkerbruin', 0, NULL, 30),
  ('haircol_chestnut', 'hairColor', '#A0522D', 'Kastanje', 0, NULL, 31),
  ('haircol_lightbrown', 'hairColor', '#D4A574', 'Lichtbruin', 0, NULL, 32),
  ('haircol_blond', 'hairColor', '#E8C07D', 'Blond', 0, NULL, 33),
  ('haircol_platinum', 'hairColor', '#FFF8DC', 'Platinablond', 0, NULL, 34),
  ('haircol_red', 'hairColor', '#C41E3A', 'Rood', 0, NULL, 35),
  ('haircol_coral', 'hairColor', '#FF6B6B', 'Koraal', 0, NULL, 36),
  ('haircol_orange', 'hairColor', '#D97848', 'Oranje', 0, NULL, 37),
  ('haircol_green', 'hairColor', '#5F947D', 'Groen', 0, NULL, 38),
  ('eyecol_dark', 'eyeColor', '#08283B', 'Donker', 0, NULL, 39),
  ('eyecol_brown', 'eyeColor', '#8B4513', 'Bruin', 0, NULL, 40),
  ('eyecol_green', 'eyeColor', '#5F947D', 'Groen', 0, NULL, 41),
  ('eyecol_blue', 'eyeColor', '#445865', 'Blauwgrijs', 0, NULL, 42),
  ('eyecol_amber', 'eyeColor', '#D7C95F', 'Amber', 0, NULL, 43),
  ('shirt_basic', 'shirtStyle', 't-shirt', 'Basis T-Shirt', 0, NULL, 44),
  ('shirt_tank', 'shirtStyle', 'tank', 'Tanktop', 50, NULL, 45),
  ('shirt_polo', 'shirtStyle', 'polo', 'Polo Shirt', 75, NULL, 46),
  ('shirt_sweater', 'shirtStyle', 'sweater', 'Trui', 125, NULL, 47),
  ('shirt_hoodie', 'shirtStyle', 'hoodie', 'Hoodie', 150, NULL, 48),
  ('shirt_flannel', 'shirtStyle', 'flannel', 'Flanellen Hemd', 150, NULL, 49),
  ('shirt_varsity', 'shirtStyle', 'varsity', 'College Jacket', 175, NULL, 50),
  ('shirt_jersey', 'shirtStyle', 'jersey', 'Sport Jersey', 175, NULL, 51),
  ('shirt_denim', 'shirtStyle', 'denim', 'Denim Jasje', 200, NULL, 52),
  ('shirt_track', 'shirtStyle', 'trackjacket', 'Trainingsjack', 200, NULL, 53),
  ('shirt_blazer', 'shirtStyle', 'blazer', 'Blazer', 300, NULL, 54),
  ('shirt_bomber', 'shirtStyle', 'bomber', 'Bomber Jacket', 350, NULL, 55),
  ('shirt_puffer', 'shirtStyle', 'puffer', 'Puffer Jacket', 375, NULL, 56),
  ('shirt_leather', 'shirtStyle', 'leather', 'Leren Jas', 400, NULL, 57),
  ('shirt_kimono', 'shirtStyle', 'kimono', 'Kimono', 450, NULL, 58),
  ('acc_suit_diamond', 'shirtStyle', 'suit_diamond', 'Diamanten Pak', 5000, NULL, 59),
  ('pants_jeans', 'pantsStyle', 'standard', 'Jeans', 0, NULL, 60),
  ('pants_shorts', 'pantsStyle', 'shorts', 'Korte Broek', 50, NULL, 61),
  ('pants_chinos', 'pantsStyle', 'chinos', 'Chino', 75, NULL, 62),
  ('pants_joggers', 'pantsStyle', 'joggers', 'Joggingbroek', 100, NULL, 63),
  ('pants_sweat', 'pantsStyle', 'sweatpants', 'Sweatpants', 100, NULL, 64),
  ('pants_skinny', 'pantsStyle', 'skinny', 'Skinny Jeans', 125, NULL, 65),
  ('pants_skirt', 'pantsStyle', 'skirt', 'Rok', 125, NULL, 66),
  ('pants_cargo', 'pantsStyle', 'cargo', 'Cargo Broek', 150, NULL, 67),
  ('pants_baggy', 'pantsStyle', 'baggy', 'Baggy Pants', 150, NULL, 68),
  ('pants_ripped', 'pantsStyle', 'ripped', 'Gescheurde Jeans', 175, NULL, 69),
  ('pants_pleated', 'pantsStyle', 'pleated', 'Plooirok', 175, NULL, 70),
  ('pants_formal', 'pantsStyle', 'formal', 'Nette Broek', 200, NULL, 71),
  ('acc_none', 'accessory', 'none', 'Geen', 0, NULL, 72),
  ('acc_bandana', 'accessory', 'bandana', 'Bandana', 75, NULL, 73),
  ('acc_glasses', 'accessory', 'glasses', 'Coole Bril', 100, NULL, 74),
  ('acc_beanie', 'accessory', 'beanie', 'Muts', 100, NULL, 75),
  ('acc_scarf', 'accessory', 'scarf', 'Sjaal', 100, NULL, 76),
  ('acc_cap', 'accessory', 'cap', 'Pet', 125, NULL, 77),
  ('acc_bowtie', 'accessory', 'bowtie', 'Vlinderdas', 125, NULL, 78),
  ('acc_sunglasses', 'accessory', 'sunglasses', 'Zonnebril', 150, NULL, 79),
  ('acc_satchel', 'accessory', 'satchel', 'Schoudertas', 150, NULL, 80),
  ('acc_tie', 'accessory', 'tie', 'Stropdas', 150, NULL, 81),
  ('acc_backpack', 'accessory', 'backpack', 'Rugzak', 175, NULL, 82),
  ('acc_necklace', 'accessory', 'necklace', 'Ketting', 175, NULL, 83),
  ('acc_earbuds', 'accessory', 'earbuds', 'Oordopjes', 200, NULL, 84),
  ('acc_watch', 'accessory', 'watch', 'Horloge', 200, NULL, 85),
  ('acc_headphones', 'accessory', 'headphones', 'Koptelefoon', 250, NULL, 86),
  ('acc_smartwatch', 'accessory', 'smartwatch', 'Smartwatch', 350, NULL, 87),
  ('acc_chain', 'accessory', 'chain', 'Gouden Ketting', 400, NULL, 88),
  ('acc_shield', 'accessory', 'shield', 'Schild', 400, NULL, 89),
  ('acc_sword', 'accessory', 'sword', 'Zwaard', 450, NULL, 90),
  ('acc_skate', 'accessory', 'skateboard', 'Skateboard', 500, NULL, 91),
  ('acc_cape', 'accessory', 'cape', 'Cape', 500, NULL, 92),
  ('acc_halo', 'accessory', 'halo', 'Halo', 600, NULL, 93),
  ('acc_guitar', 'accessory', 'guitar', 'Gitaar', 600, NULL, 94),
  ('acc_robot_arm', 'accessory', 'robot_arm', 'Robot Arm', 650, NULL, 95),
  ('acc_wings', 'accessory', 'wings', 'Vleugels', 750, NULL, 96),
  ('acc_crown', 'accessory', 'crown', 'Kroon', 800, NULL, 97),
  ('acc_crown_gold', 'accessory', 'crown_gold', 'Gouden Kroon', 2500, NULL, 98),
  ('acc_wings_cyber', 'accessory', 'wings_cyber', 'Cyber Vleugels', 3000, NULL, 99),
  ('acc_jetpack', 'accessory', 'jetpack', 'Jetpack', 3500, NULL, 100),
  ('pet_none', 'pet', 'none', 'Geen', 0, NULL, 101),
  ('pet_dog_free', 'pet', 'pet_dog', 'Hond', 0, NULL, 102),
  ('pet_cat_free', 'pet', 'pet_cat', 'Kat', 0, NULL, 103),
  ('pet_duck_free', 'pet', 'pet_duck', 'Eendje', 0, NULL, 104),
  ('pet_robo_free', 'pet', 'pet_robo', 'Robot', 0, NULL, 105),
  ('expr_neutral', 'expression', 'neutral', 'Neutraal', 0, NULL, 106),
  ('expr_happy', 'expression', 'happy', 'Blij', 0, NULL, 107),
  ('expr_cool', 'expression', 'cool', 'Cool', 100, NULL, 108),
  ('expr_surprised', 'expression', 'surprised', 'Verrast', 100, NULL, 109),
  ('pose_idle', 'pose', 'idle', 'Standaard', 0, NULL, 110),
  ('pose_wave', 'pose', 'wave', 'Zwaaien', 75, NULL, 111),
  ('pose_peace', 'pose', 'peace', 'Peace', 100, NULL, 112),
  ('pose_dab', 'pose', 'dab', 'Dab', 150, NULL, 113),
  ('shirtcol_terracotta', 'shirtColor', '#D97848', 'Terracotta', 0, NULL, 114),
  ('shirtcol_mosterd', 'shirtColor', '#D7C95F', 'Mosterd', 0, NULL, 115),
  ('shirtcol_zeegroen', 'shirtColor', '#5F947D', 'Zeegroen', 0, NULL, 116),
  ('shirtcol_donkergroen', 'shirtColor', '#0B453F', 'Donkergroen', 0, NULL, 117),
  ('shirtcol_nachtblauw', 'shirtColor', '#08283B', 'Nachtblauw', 0, NULL, 118),
  ('shirtcol_leisteen', 'shirtColor', '#445865', 'Leisteen', 0, NULL, 119),
  ('shirtcol_zand', 'shirtColor', '#E7D8BD', 'Zand', 0, NULL, 120),
  ('shirtcol_wit', 'shirtColor', '#ffffff', 'Wit', 0, NULL, 121),
  ('pantscol_terracotta', 'pantsColor', '#D97848', 'Terracotta', 0, NULL, 122),
  ('pantscol_mosterd', 'pantsColor', '#D7C95F', 'Mosterd', 0, NULL, 123),
  ('pantscol_zeegroen', 'pantsColor', '#5F947D', 'Zeegroen', 0, NULL, 124),
  ('pantscol_donkergroen', 'pantsColor', '#0B453F', 'Donkergroen', 0, NULL, 125),
  ('pantscol_nachtblauw', 'pantsColor', '#08283B', 'Nachtblauw', 0, NULL, 126),
  ('pantscol_leisteen', 'pantsColor', '#445865', 'Leisteen', 0, NULL, 127),
  ('pantscol_zand', 'pantsColor', '#E7D8BD', 'Zand', 0, NULL, 128),
  ('pantscol_wit', 'pantsColor', '#ffffff', 'Wit', 0, NULL, 129),
  ('shoecol_terracotta', 'shoeColor', '#D97848', 'Terracotta', 0, NULL, 130),
  ('shoecol_mosterd', 'shoeColor', '#D7C95F', 'Mosterd', 0, NULL, 131),
  ('shoecol_zeegroen', 'shoeColor', '#5F947D', 'Zeegroen', 0, NULL, 132),
  ('shoecol_donkergroen', 'shoeColor', '#0B453F', 'Donkergroen', 0, NULL, 133),
  ('shoecol_nachtblauw', 'shoeColor', '#08283B', 'Nachtblauw', 0, NULL, 134),
  ('shoecol_leisteen', 'shoeColor', '#445865', 'Leisteen', 0, NULL, 135),
  ('shoecol_zand', 'shoeColor', '#E7D8BD', 'Zand', 0, NULL, 136),
  ('shoecol_wit', 'shoeColor', '#ffffff', 'Wit', 0, NULL, 137),
  ('acccol_terracotta', 'accessoryColor', '#D97848', 'Terracotta', 0, NULL, 138),
  ('acccol_mosterd', 'accessoryColor', '#D7C95F', 'Mosterd', 0, NULL, 139),
  ('acccol_zeegroen', 'accessoryColor', '#5F947D', 'Zeegroen', 0, NULL, 140),
  ('acccol_donkergroen', 'accessoryColor', '#0B453F', 'Donkergroen', 0, NULL, 141),
  ('acccol_nachtblauw', 'accessoryColor', '#08283B', 'Nachtblauw', 0, NULL, 142),
  ('acccol_leisteen', 'accessoryColor', '#445865', 'Leisteen', 0, NULL, 143),
  ('acccol_zand', 'accessoryColor', '#E7D8BD', 'Zand', 0, NULL, 144),
  ('acccol_wit', 'accessoryColor', '#ffffff', 'Wit', 0, NULL, 145)
ON CONFLICT (id) DO UPDATE SET
  slot       = EXCLUDED.slot,
  value      = EXCLUDED.value,
  label      = EXCLUDED.label,
  price      = EXCLUDED.price,
  gender     = EXCLUDED.gender,
  sort_order = EXCLUDED.sort_order,
  is_active  = true,
  updated_at = now();

-- Items die uit de catalogus verdwenen zijn worden gedeactiveerd, nooit
-- verwijderd: leerlingen kunnen ze bezitten en dat bezit moet blijven kloppen.
UPDATE public.avatar_shop_items
   SET is_active = false, updated_at = now()
 WHERE id <> ALL (ARRAY['gender_male', 'gender_female', 'model_std', 'model_slim', 'model_bot', 'skin_pale', 'skin_fair', 'skin_tan', 'skin_olive', 'skin_brown', 'skin_dark', 'skin_ebony', 'hair_short', 'hair_spiky', 'hair_buzzcut', 'hair_messy', 'hair_curls', 'hair_fade', 'hair_sidepart', 'hair_afro_m', 'hair_mohawk', 'hair_pigtails', 'hair_long', 'hair_bob', 'hair_braids', 'hair_curls_f', 'hair_ponytail', 'hair_bun', 'hair_afro_f', 'haircol_black', 'haircol_darkbrown', 'haircol_chestnut', 'haircol_lightbrown', 'haircol_blond', 'haircol_platinum', 'haircol_red', 'haircol_coral', 'haircol_orange', 'haircol_green', 'eyecol_dark', 'eyecol_brown', 'eyecol_green', 'eyecol_blue', 'eyecol_amber', 'shirt_basic', 'shirt_tank', 'shirt_polo', 'shirt_sweater', 'shirt_hoodie', 'shirt_flannel', 'shirt_varsity', 'shirt_jersey', 'shirt_denim', 'shirt_track', 'shirt_blazer', 'shirt_bomber', 'shirt_puffer', 'shirt_leather', 'shirt_kimono', 'acc_suit_diamond', 'pants_jeans', 'pants_shorts', 'pants_chinos', 'pants_joggers', 'pants_sweat', 'pants_skinny', 'pants_skirt', 'pants_cargo', 'pants_baggy', 'pants_ripped', 'pants_pleated', 'pants_formal', 'acc_none', 'acc_bandana', 'acc_glasses', 'acc_beanie', 'acc_scarf', 'acc_cap', 'acc_bowtie', 'acc_sunglasses', 'acc_satchel', 'acc_tie', 'acc_backpack', 'acc_necklace', 'acc_earbuds', 'acc_watch', 'acc_headphones', 'acc_smartwatch', 'acc_chain', 'acc_shield', 'acc_sword', 'acc_skate', 'acc_cape', 'acc_halo', 'acc_guitar', 'acc_robot_arm', 'acc_wings', 'acc_crown', 'acc_crown_gold', 'acc_wings_cyber', 'acc_jetpack', 'pet_none', 'pet_dog_free', 'pet_cat_free', 'pet_duck_free', 'pet_robo_free', 'expr_neutral', 'expr_happy', 'expr_cool', 'expr_surprised', 'pose_idle', 'pose_wave', 'pose_peace', 'pose_dab', 'shirtcol_terracotta', 'shirtcol_mosterd', 'shirtcol_zeegroen', 'shirtcol_donkergroen', 'shirtcol_nachtblauw', 'shirtcol_leisteen', 'shirtcol_zand', 'shirtcol_wit', 'pantscol_terracotta', 'pantscol_mosterd', 'pantscol_zeegroen', 'pantscol_donkergroen', 'pantscol_nachtblauw', 'pantscol_leisteen', 'pantscol_zand', 'pantscol_wit', 'shoecol_terracotta', 'shoecol_mosterd', 'shoecol_zeegroen', 'shoecol_donkergroen', 'shoecol_nachtblauw', 'shoecol_leisteen', 'shoecol_zand', 'shoecol_wit', 'acccol_terracotta', 'acccol_mosterd', 'acccol_zeegroen', 'acccol_donkergroen', 'acccol_nachtblauw', 'acccol_leisteen', 'acccol_zand', 'acccol_wit']);
